# Generated by Django 5.2.5 on 2025-09-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can View User'), ('can_edit', 'Can Edit User'), ('can_delete', 'Can Delete User'), ('can_create', 'Can Create User')]},
        ),
    ]
